---
- name: Configure Ubuntu Server
  hosts: 192.168.100.24
  become: yes 

  tasks:
    - name: Create new user cloudru
      user:
        name: cloudru
        password: "{{ 'cloudpass' | password_hash('sha512') }}"
        createhome: yes

    - name: Disable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify:
        - restart ssh
        
    - name: Set authorized key in alternate location
      ansible.posix.authorized_key:
        user: cloudru
        state: present
        key: "{{ lookup('file', '/home/administrator/project/id_rsa.pub') }}"
        path: ~/.ssh/authorized_key
        manage_dir: false


  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted
