apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-listener-v1.fullname" . }}-service
  labels:
    {{- include "app-listener-v1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "app-listener-v1.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
